<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
  targetNamespace="http://www.porto.com/re/exception"
  xmlns:ns2="http://www.portoseguro.com.br/foundation/PortoSeguroMessage/v1_0">
  <types>
    <xs:schema>
      <xs:import
        namespace="http://www.portoseguro.com.br/foundation/PortoSeguroMessage/v1_0"
        schemaLocation="FaultV1_0.xsd" />
    </xs:schema>
  </types>

  <message name="PortoFaultException">
    <part name="fault" element="ns2:portoSeguroFaultInfo"></part>
  </message>

</wsdl:definitions>